GEMINI_API_KEY = "AQ.Ab8RN6JKq0l_qTun9MF5hRwIbEqxyu7ZxoXlmAhr7Z8ATjHoLw"
CLOUDINARY_CLOUD_NAME = "fbdxr6lx"
CLOUDINARY_API_KEY = "159654323459224"
CLOUDINARY_API_SECRET = "rpCAXKbdkKMS-NSVvrCIH2YEuaQ"
